#!/usr/bin/env python

import csv
import sys

postcode = sys.argv[1]

with open('4pp.csv', 'r') as csv_file:
    postcode_csv = csv.reader(csv_file)

    for row in postcode_csv:
        if row[1] == postcode:
            gemeente = row[2]
            print(gemeente)


